Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)

# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**

In [68]:
import numpy as np

In [69]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it

x = np.array([1, 2, 3, 4, 5])
print(x)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it

y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [70]:
# Write a NumPy function to create an array with random values of shape [3,4]

from numpy import random

x = random.randint(100, size=(3, 4))
print(x)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

y = np.zeros((3, 4))
print(y)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]

z = np.ones((3, 4))
print(z)

[[52 23 86 18]
 [95 47 81 16]
 [89 60 95 36]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [71]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals

x = np.arange(0, 100, 2)
print(x)

# Hint : Use np.arange or np.linspace

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]

### Basic array operations
- algebraic operations
- logical operations

In [72]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [73]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'

c = np.add(a, b)
d = np.subtract(a, b)
e = np.multiply(a, b)
f = np.divide(a, b)

print(c)
print(d)
print(e)
print(f)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]

In [74]:
# Write a NumPy function to get the sum of the array 'a' along axis=0

g = np.sum(a, axis=0)
print(g)

# Write a NumPy function to get the sum of the array 'a' along axis=1

h = np.sum(a, axis=1)
print(h)

[ 6 17 14]
[10 13 14]

In [75]:
# Write a NumPy function to reverse the array 'a'

i = np.flip(a)
print(i)

# Write a NumPy function to reverse the array 'a' along axis=0

j = np.flip(a, axis=0)
print(j)

# Write a NumPy function to reverse the array 'a' along axis=1

k = np.flip(a, axis=1)
print(k)

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]

### Sorting and concatenation
- sort arrays
- join multiple arrays

In [76]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [77]:
# Write a NumPy function to sort the array 'a'

c = np.sort(a)
print(c)

# Write a NumPy function to sort the array 'a' along axis=0

d = np.sort(a, axis=0)
print(d)

# Write a NumPy function to sort the array 'a' along axis=1

e = np.sort(a, axis=1)
print(e)

# Write a NumPy function to sort the array 'a' in descending order along axis=0

f = np.sort(a, axis=0)
f = f[::-1]
print(f)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]

In [78]:
# Write a NumPy function to argsort the array along axis=0

g = np.argsort(a, axis=0)
print(g)

# Write a NumPy function to argsort the array along axis=1

h = np.argsort(a, axis=1)
print(h)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]

In [79]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'

i = np.concatenate((a, b))
print(i)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

j = np.concatenate((a, b), axis=0)
print(j)

# Note: You can do the same function using stacking, discover and try that :)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [80]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [81]:
# Write a NumPy function to get the Number of dimensions

b = np.ndim(a)
print(b)

# Write a NumPy function to get the Shape of the array

c = np.shape(a)
print(c)

# Write a NumPy function to get the Size of the array

d = np.size(a)
print(d)

2
(3, 3)
9

In [82]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)

e =  np.reshape(a, (1, 9))
print(e)

[[4 6 8 9 3 1 1 8 5]]

In [83]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this

# Method 1
f = np.expand_dims(a, axis=0)
print(f)

# Method 2
g = np.expand_dims(a, axis=1)
print(g)

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [84]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [85]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range

int_index = 2
tuple_index = (0, 1)
range_index = range(1,3)

print(a[int_index])
print(a[tuple_index])
print(a[range_index])

#slicing

print(a[0:2:1])

[1 8 5]
6
[[0 3 1]
 [1 8 5]]
[[4 6 0]
 [0 3 1]]

In [86]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4


selections1 = np.select([a > 4], [a])
print(selections1)


# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2

selections2 = np.select([(a-4)%2 == 0], [a])
print(selections2)

[[0 6 0]
 [0 0 0]
 [0 8 5]]
[[4 6 0]
 [0 0 0]
 [0 8 0]]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [87]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [88]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1

b = a.copy()
print(b+1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.

#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [89]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [90]:
# Write a Pandas function to drop rows that contain a missing value.

import pandas as pd
df = pd.read_csv(url, header=None)
df.rename(columns={0:'sepallength', 1:'sepalwidth', 2:'petallength', 3:'petalwidth', 4:'species'}, inplace=True)

df.dropna(inplace=True)

print(df)

     sepallength  sepalwidth  petallength  petalwidth         species
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [91]:
# Write a Pandas function to find the correlation between the first two columns.

c = df['sepallength'].corr(df['sepalwidth'])
print(c)

-0.10936924995064937

In [92]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.

mean = df['petallength'].mean()
median = df['petallength'].median()
stddev = df['petallength'].std()

print(mean)
print(median)
print(stddev)

3.758666666666666
4.35
1.7644204199522626

In [93]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

volumes = list()
for i in range(0, 150):
    volumes.append(3.14 * df['petallength'][i] * (df['sepallength'][i] ** 2)/3)

df.insert(4, "volume", volumes, True)

print(df)



# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

     sepallength  sepalwidth  petallength  petalwidth      volume  \
0            5.1         3.5          1.4         0.2   38.113320
1            4.9         3.0          1.4         0.2   35.182653
2            4.7         3.2          1.3         0.2   30.057127
3            4.6         3.1          1.5         0.2   33.221200
4            5.0         3.6          1.4         0.2   36.633333
..           ...         ...          ...         ...         ...
145          6.7         3.0          5.2         2.3  244.321307
146          6.3         2.5          5.0         1.9  207.711000
147          6.5         3.0          5.2         2.0  229.952667
148          6.2         3.4          5.4         2.3  217.262880
149          5.9         3.0          5.1         1.8  185.815780

            species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [94]:
x = np.arange(4, dtype=np.int64)
xshape = np.shape(x)

y = np.ones(shape=xshape, dtype=np.int64)
print(y)

[1 1 1 1]

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [95]:
x = np.arange(1, 10)
a = x[:4]
b = x[4:6]
c = x[6:]

print(a)
print(b)
print(c)

[1 2 3 4]
[5 6]
[7 8 9]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [96]:
x = np.random.randint(1, 10, size=(2, 5))
print(x)
maxvalues = np.max(x, axis=1)
minvalues = np.min(x, axis=1)
print(maxvalues, minvalues)

[[4 1 6 5 4]
 [9 8 5 4 2]]
[6 9] [1 2]

### Pandas

Run the following load command and solve the following questions

In [97]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [98]:
df = pd.read_csv(url, header=None)

df.rename(columns={0:'sepallength', 1:'sepalwidth', 2:'petallength', 3:'petalwidth', 4:'species'}, inplace=True)

uniqspecies = list()
for i in range(0, len(df['species'])):
    if df['species'][i] in uniqspecies:
        continue
    else:
        uniqspecies.append(df['species'][i])

print(len(uniqspecies))

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [99]:
for i in range(0, len(df['petallength'])):
    if df['petallength'][i] < 3:
        df['petallength'][i] = 'small'
    elif df['petallength'][i] >= 3 and df['petallength'][i] < 5:
        df['petallength'][i] = 'medium'
    else:
        df['petallength'][i] = 'large'

print(df)

     sepallength  sepalwidth petallength  petalwidth         species
0            5.1         3.5       small         0.2     Iris-setosa
1            4.9         3.0       small         0.2     Iris-setosa
2            4.7         3.2       small         0.2     Iris-setosa
3            4.6         3.1       small         0.2     Iris-setosa
4            5.0         3.6       small         0.2     Iris-setosa
..           ...         ...         ...         ...             ...
145          6.7         3.0       large         2.3  Iris-virginica
146          6.3         2.5       large         1.9  Iris-virginica
147          6.5         3.0       large         2.0  Iris-virginica
148          6.2         3.4       large         2.3  Iris-virginica
149          5.9         3.0       large         1.8  Iris-virginica

[150 rows x 5 columns]

<ipython-input-99-25ffad8a94b2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['petallength'][i] = 'small'

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [100]:
df = pd.read_csv(url, header=None)

df.rename(columns={0:'sepallength', 1:'sepalwidth', 2:'petallength', 3:'petalwidth', 4:'species'}, inplace=True)

counts = df['petallength'].value_counts()
print(counts.index[0])

1.5